name: 'ecommerce_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_lakehouse'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_lakehouse:
    staging:
      +materialized: view
      
    silver:
      +materialized: incremental
      +file_format: parquet
      +partition_by: event_date
      +incremental_strategy: append
      
      # Gold layer configuration
    gold:
      core:
        +materialized: table
        +file_format: parquet
        +schema: gold
      funnel:
        +materialized: table
        +file_format: parquet
        +schema: gold
      traffic:
        +materialized: incremental
        +file_format: parquet
        +partition_by: event_date
        +incremental_strategy: append
        +schema: gold